import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {OBJLoader} from 'three/addons/loaders/OBJLoader.js';
const mount=document.querySelector('#scene'),statusEl=document.querySelector('#status'),scene=new THREE.Scene();
scene.background=new THREE.Color(0x93c5e8);scene.fog=new THREE.Fog(0x93c5e8,1800,5200);
const camera=new THREE.PerspectiveCamera(48,1,.1,10000);camera.position.set(1450,1050,1450);
const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;mount.append(renderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.target.set(-32,0,-21);controls.maxPolarAngle=1.52;controls.minDistance=180;controls.maxDistance=4500;
scene.add(new THREE.HemisphereLight(0xd9edff,0x3b492d,2.5));const sun=new THREE.DirectionalLight(0xffe9bf,3.2);sun.position.set(-1000,1800,800);sun.castShadow=true;scene.add(sun);
const grid=new THREE.GridHelper(4096,128,0x50555a,0x3b4045);grid.position.y=16.2;scene.add(grid);let plate;
const diffuse=new THREE.TextureLoader().load('assets/baseplate-diffuse.png');diffuse.wrapS=diffuse.wrapT=THREE.RepeatWrapping;diffuse.colorSpace=THREE.SRGBColorSpace;diffuse.anisotropy=renderer.capabilities.getMaxAnisotropy();
new OBJLoader().load('assets/baseplate.obj',o=>{plate=o;o.traverse(c=>{if(c.isMesh){const isTop=c.name==='Baseplate2';c.material=new THREE.MeshStandardMaterial({color:isTop?0xffffff:0x303237,map:isTop?diffuse:null,roughness:.92});c.receiveShadow=true}});scene.add(o);statusEl.textContent='Baseplate + Studio texture loaded'},null,()=>statusEl.textContent='Could not load baseplate');
new ResizeObserver(()=>{const w=mount.clientWidth,h=mount.clientHeight;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h,false)}).observe(mount);renderer.setAnimationLoop(()=>{controls.update();renderer.render(scene,camera)});
const $=s=>document.querySelector(s),toast=m=>{const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1700)};
$('#color').value='#ffffff';
$('#home').onclick=()=>{camera.position.set(1450,1050,1450);controls.target.set(-32,0,-21)};$('#grid').onclick=()=>grid.visible=!grid.visible;
$('#add').onclick=()=>{const p=new THREE.Mesh(new THREE.BoxGeometry(160,160,160),new THREE.MeshStandardMaterial({color:0xf2c94c}));p.position.set((Math.random()-.5)*700,96,(Math.random()-.5)*700);p.castShadow=true;scene.add(p);toast('Part added')};
$('#color').oninput=e=>plate?.traverse(c=>{if(c.isMesh&&c.name==='Baseplate2')c.material.color.set(e.target.value)});document.querySelectorAll('.toggle').forEach(b=>b.onclick=()=>b.classList.toggle('on'));
const pair=$('#pair');$('#pairBtn').onclick=()=>pair.showModal();$('#close').onclick=()=>pair.close();$('#code').onclick=()=>{navigator.clipboard?.writeText('BX7K-R4M2');toast('Pair code copied')};
const prompt=$('#prompt'),messages=$('#messages');function send(){const v=prompt.value.trim();if(!v)return;const safe=v.replace(/[<>&]/g,x=>({'<':'&lt;','>':'&gt;','&':'&amp;'}[x]));messages.insertAdjacentHTML('beforeend',`<article><b>Y</b><p><small>YOU</small>${safe}</p></article><article><b>B</b><p><small>BLOXY</small>Blueprint ready for backend generation. Pair Studio when the secure API is connected.</p></article>`);prompt.value='';messages.scrollTop=messages.scrollHeight}$('#send').onclick=send;prompt.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}};document.querySelectorAll('.ideas button').forEach(b=>b.onclick=()=>{prompt.value=b.textContent;prompt.focus()});
