"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
type Action={type:string;name:string;summary:string};

export default function Home(){
 const [connected,setConnected]=useState(false),[prompt,setPrompt]=useState(""),[code,setCode]=useState("LOADING"),[webToken,setWebToken]=useState(""),[bits,setBits]=useState<number|null>(null);
 const [messages,setMessages]=useState(["Describe a game system. I’ll create a safe blueprint before anything changes."]),[actions,setActions]=useState<Action[]>([]),[busy,setBusy]=useState(false);
 useEffect(()=>{fetch("/api/pair/start",{method:"POST"}).then(r=>r.json()).then(x=>{setCode(x.pairCode);setWebToken(x.webToken)}).catch(()=>setCode("OFFLINE"))},[]);
 useEffect(()=>{if(!webToken||connected)return;const timer=setInterval(()=>fetch("/api/pair/status",{headers:{Authorization:`Bearer ${webToken}`}}).then(r=>r.json()).then(x=>{if(x.status==="connected")setConnected(true)}).catch(()=>{}),2000);return()=>clearInterval(timer)},[webToken,connected]);
 useEffect(()=>{if(!webToken)return;const load=()=>fetch("/api/wallet",{headers:{Authorization:`Bearer ${webToken}`}}).then(r=>r.json()).then(x=>{if(typeof x.balanceBits==="number")setBits(x.balanceBits)}).catch(()=>{});load();const timer=setInterval(load,15000);return()=>clearInterval(timer)},[webToken]);
 const send=async()=>{const text=prompt.trim();if(!text||busy)return;setMessages(m=>[...m,text]);setPrompt("");if(!connected){setMessages(m=>[...m,"Pair Roblox Studio first, then I can generate the blueprint."]);return}setBusy(true);try{const r=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${webToken}`},body:JSON.stringify({prompt:text})});const x=await r.json();if(typeof x.balanceBits==="number")setBits(x.balanceBits);if(!r.ok)throw new Error(x.error||"Generation failed");setActions(x.actions);setMessages(m=>[...m,`Blueprint ready: ${x.actions.length} safe actions · ${x.bitsCharged} Bit used. Review it in Studio before applying.`])}catch(e){setMessages(m=>[...m,e instanceof Error?e.message:"Generation failed"])}finally{setBusy(false)}};
 return <main><header><Link className="brand" href="/"><b>B</b> BLOXY</Link><div className="state"><i className={connected?"on":""}/>{connected?"Studio paired":"Waiting for Studio"}</div><button className="usage" title="1 Bit equals one cent of AI usage"><strong>{bits??"—"}</strong> Bits <span>· ${(bits===null?0:bits/100).toFixed(2)} value</span></button></header>
 <section className="workspace"><aside className="intro"><div><small>STUDIO BRIDGE</small><h1>Build Roblox<br/><em>through conversation.</em></h1><p>Pair the Studio plugin once. Every build arrives as a visible blueprint you approve, revise, or discard.</p></div><div className="pair"><div><span>PAIRING CODE</span><span className="live">LIVE · 60 MIN</span></div><button title="Copy code" onClick={()=>navigator.clipboard?.writeText(code)}>{code}</button><p>Enter this code in the Bloxy Roblox Studio plugin.</p><button className="connect" disabled>{connected?"Connected to Roblox Studio":"Waiting for plugin"}</button></div><div className="safe"><b>◇</b><p><strong>Nothing applies silently</strong><br/>Scripts are scanned. Every change has one-click undo.</p></div></aside>
 <section className="chat"><div className="label"><span>BUILD CHAT</span><span>GEMINI 3.7 FLASH · QUALITY</span></div><div className="messages">{messages.map((m,i)=><div className={i%2?"message you":"message"} key={i}><small>{i%2?"YOU":"BLOXY"}</small><p>{m}</p></div>)}</div><div className="composer"><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Build a neon tower lobby with a round system..."/><div><span>↵ send · shift ↵ new line</span><button onClick={send} disabled={busy}>{busy?"Planning...":"Generate blueprint →"}</button></div></div></section>
 <aside className="blueprint"><div className="label"><span>BUILD BLUEPRINT</span><span>{String(actions.length).padStart(2,"0")} ACTIONS</span></div><div className="grid"><div className="tower a"/><div className="tower b"/><div className="tower c"/><span>LIVE / PREVIEW</span><b>SAFE PREVIEW</b></div><div className="actions">{actions.length?actions.map((a,i)=><article key={i}><small>{String(i+1).padStart(2,"0")}</small><div><i>{a.type.toUpperCase()}</i><strong>{a.name}</strong><p>{a.summary}</p></div><b>✓</b></article>):<article><small>—</small><div><strong>No blueprint yet</strong><p>Your approved plan will appear here and in Studio.</p></div></article>}</div><div className="apply"><button>Revise in chat</button><button disabled>Apply inside Studio</button></div></aside></section></main>
}
